name: Deploy Express App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/emnd/
            
            # Load NVM and set PATH correctly
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"

            export PATH="$HOME/.nvm/versions/node/v22.6.0/bin:$PATH"

            # Debugging: Print node, yarn, and pm2 paths
            which node
            which yarn
            which pm2

            # Pull latest code
            git pull origin main

            # Install dependencies
            yarn install --frozen-lockfile
            
            # Build the application
            yarn build

            # Restart the app using PM2
            pm2 reload my-app
