name: Deploy Express App

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/emnd/
            
            # Load NVM and set PATH correctly
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
            export PATH="$HOME/.nvm/versions/node/v22.6.0/bin:$PATH"

            # Detect the branch and switch accordingly
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              BRANCH="main"
            else
              BRANCH="staging"
            fi

            echo "Deploying to $BRANCH branch..."

            # Switch to the correct branch and pull updates
            git checkout $BRANCH
            git pull origin $BRANCH

            # Install dependencies
            yarn install --frozen-lockfile
            
            # Build the application
            yarn build

            # Restart the app using PM2
            pm2 reload my-app
