- name: Deploy to Staging
  if: github.ref == 'refs/heads/staging'
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.STAGING_HOST }}
    username: ${{ secrets.USER }}
    key: ${{ secrets.SSH_PRI_KEY }}
    port: 22
    script: |
      # Manually source the nvm script to ensure node and yarn are available
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      # Optionally, add yarn and pm2 to PATH if they are installed globally
      export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

      echo "Current user: $(whoami)"
      echo "Home directory: $HOME"
      echo "Current directory: $(pwd)"
      echo "Shell: $SHELL"
      echo "PATH: $PATH"

      echo "Changing directory to the app folder"
      cd /var/www/emnd/ || exit 1

      echo "Pulling latest changes from remote"
      git pull || exit 1

      echo "Checking out staging branch"
      git checkout staging || exit 1
      
      echo "Pulling latest updates from remote"
      git pull origin staging || exit 1
      
      echo "Installing dependencies"
      yarn install || { echo "yarn install failed"; exit 1; }
      
      echo "Building the app"
      yarn build || { echo "yarn build failed"; exit 1; }
      
      echo "Reloading the app with PM2"
      pm2 reload my-app || { echo "pm2 reload failed"; exit 1; }
