name: Deploy Express App

on:
  push:
    branches:
      - staging   # Staging branch for staging environment
      - main      # Main branch for production environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH: "${{ github.ref == 'refs/heads/main' && 'main' || 'staging' }}"
      DEPLOY_HOST: "${{ github.ref == 'refs/heads/main' && secrets.HOST || secrets.STAGING_HOST }}"
      USE_NVM: "${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRI_KEY }}
          script: |
            #!/bin/bash
            set -e

            echo "Starting deployment for branch '$BRANCH' on host '$DEPLOY_HOST'"
            echo "Current user: $(whoami)"
            echo "Home directory: $HOME"
            echo "Current directory: $(pwd)"
            echo "Shell: $SHELL"
            echo "PATH: $PATH"

            # Set up Node environment based on USE_NVM flag
            if [ "$USE_NVM" == "true" ]; then
              echo "Using NVM for Node.js"
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
              [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
              nvm use default || nvm use node || echo "Node already active"
              echo "Node version (via NVM): $(node -v)"
            else
              echo "Using system-installed Node.js"
              export PATH="/usr/bin:$PATH"
              echo "Node version (system): $(node -v)"
            fi

            echo "Yarn location: $(which yarn) and version: $(yarn --version)"
            echo "PM2 location: $(which pm2)"

            cd /var/www/emnd/ || { echo "Failed to change directory"; exit 1; }

            echo "Resetting any local changes..."
            git reset --hard HEAD

            echo "Deploying to branch: $BRANCH"
            git checkout $BRANCH
            git pull origin $BRANCH

            yarn --version || npm install -g yarn

            echo "Installing dependencies"
            yarn install

            echo "Building the app"
            yarn build

            echo "Reloading the app with PM2"
            pm2 reload my-app
