name: Deploy

on:
  push:
    branches:
      - staging   # Staging branch for staging environment
      - main      # Main branch for production environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    steps:
      - name: Deploy to ${{ matrix.environment }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.environment == 'staging' && secrets.STAGING_HOST || secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRI_KEY }}
          port: 22
          script: |
            echo "Starting deployment for '${{ matrix.environment }}' environment"
            echo "Current user: $(whoami)"
            echo "Home directory: $HOME"
            echo "Current directory: $(pwd)"
            echo "Shell: $SHELL"
            echo "PATH: $PATH"

            # Change to app directory
            cd /var/www/emnd/ || { echo "Failed to change directory"; exit 1; }

            # Pull latest changes and checkout the proper branch
            echo "Pulling latest changes from remote"
            git pull || { echo "git pull failed"; exit 1; }

            if [ "${{ matrix.environment }}" = "staging" ]; then
              echo "Checking out staging branch"
              git checkout staging || { echo "Failed to checkout staging"; exit 1; }
              echo "Pulling latest updates from remote (staging)"
              git pull origin staging || { echo "git pull origin staging failed"; exit 1; }
            else
              echo "Checking out main branch"
              git checkout main || { echo "Failed to checkout main"; exit 1; }
              echo "Pulling latest updates from remote (main)"
              git pull origin main || { echo "git pull origin main failed"; exit 1; }
            fi

            # Install dependencies
            echo "Installing dependencies"
            which yarn
            yarn install || { echo "yarn install failed"; exit 1; }

            # Build the app
            echo "Building the app"
            which yarn
            yarn build || { echo "yarn build failed"; exit 1; }

            # Reload the app with PM2
            echo "Reloading the app with PM2"
            which pm2
            pm2 reload my-app || { echo "pm2 reload failed"; exit 1; }
