name: Deploy

on:
  push:
    branches:
      - staging   # Staging branch for staging environment
      - main      # Main branch for production environment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRI_KEY }}
          port: 22
          script: |
            echo "Current user: $(whoami)"
            echo "Home directory: $HOME"
            echo "Current directory: $(pwd)"
            echo "Shell: $SHELL"
            echo "PATH: $PATH"

            echo "Changing directory to the app folder"
            cd /var/www/emnd/ || exit 1

            echo "Pulling latest changes from remote"
            git pull || exit 1

            echo "Checking out staging branch"
            git checkout staging || exit 1
            
            echo "Pulling latest updates from remote"
            git pull origin staging || exit 1
            
            echo "Installing dependencies"
            which yarn
            pwd
            yarn install || exit 1
            
            echo "Building the app"
            which yarn
            pwd
            yarn build || exit 1
            
            echo "Reloading the app with PM2"
            which pm2
            pwd
            pm2 reload my-app || exit 1

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRI_KEY }}
          port: 22
          script: |
            echo "Current user: $(whoami)"
            echo "Home directory: $HOME"
            echo "Current directory: $(pwd)"
            echo "Shell: $SHELL"
            echo "PATH: $PATH"

            echo "Changing directory to the app folder"
            cd /var/www/emnd/ || exit 1

            echo "Pulling latest changes from remote"
            git pull || exit 1

            echo "Checking out main branch"
            git checkout main || exit 1
            
            echo "Pulling latest updates from remote"
            git pull origin main || exit 1
            
            echo "Installing dependencies"
            which yarn
            pwd
            yarn install || exit 1
            
            echo "Building the app"
            which yarn
            pwd
            yarn build || exit 1
            
            echo "Reloading the app with PM2"
            which pm2
            pwd
            pm2 reload my-app || exit 1
