name: Deploy Express App

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "DEPLOY_HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
            echo "BRANCH=main" >> $GITHUB_ENV
            echo "USE_NVM=true" >> $GITHUB_ENV  # Production uses NVM
          else
            echo "DEPLOY_HOST=${{ secrets.STAGING_HOST }}" >> $GITHUB_ENV
            echo "BRANCH=staging" >> $GITHUB_ENV
            echo "USE_NVM=false" >> $GITHUB_ENV  # Staging uses global Node.js
          fi

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRI_KEY }}
          script: |
            cd /var/www/emnd/

            # Use NVM only for production
            if [ "$USE_NVM" == "true" ]; then
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
              [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
              export PATH="$HOME/.nvm/versions/node/v22.6.0/bin:$PATH"
            else
              export PATH="/usr/bin:$PATH"  # Use system-installed Node.js on staging
            fi

            # Debug: Check which versions are being used
            echo "Node.js: $(which node)"
            echo "Yarn: $(which yarn)"
            echo "PM2: $(which pm2)"

            echo "Deploying to $BRANCH branch on $DEPLOY_HOST"

            # Checkout the correct branch and pull latest code
            git checkout $BRANCH
            git pull origin $BRANCH

            # Install dependencies
            yarn install --frozen-lockfile
            
            # Build the application
            yarn build

            # Restart the app using PM2
            pm2 reload my-app
