name: Deploy Express App

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_HOST: ${{ secrets.HOST }}
          BRANCH: "main"
          USE_NVM: "true"
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRI_KEY }}
          script: |
            #!/bin/bash
            set -e
            echo "Starting deployment for branch '$BRANCH' on host '$DEPLOY_HOST'"
            echo "Current user: $(whoami)"
            echo "Home directory: $HOME"
            echo "Current directory: $(pwd)"
            echo "Shell: $SHELL"
            echo "PATH: $PATH"
           
            # Ensure NVM and Node.js are correctly loaded
            if [ "$USE_NVM" == "true" ]; then
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
              [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
              export PATH="$NVM_DIR/versions/node/$(ls $NVM_DIR/versions/node)/bin:$PATH"
            else
              export PATH="/usr/bin:$PATH"  # Use system-installed Node.js on staging
            fi

            cd /var/www/emnd/ || { echo "Failed to change directory"; exit 1; }

            echo "Resetting any local changes..."
            git reset --hard HEAD

            echo "Deploying to branch: $BRANCH"
            git checkout $BRANCH
            git pull origin $BRANCH

            yarn --version || npm install -g yarn

            echo "Installing dependencies"
            yarn install

            echo "Building the app"
            yarn build

            echo "Reloading the app with PM2"
            pm2 reload my-app

      - name: Deploy to Staging Server
        if: github.ref == 'refs/heads/staging'
        env:
          DEPLOY_HOST: ${{ secrets.STAGING_HOST }}
          BRANCH: "staging"
          USE_NVM: "false"
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRI_KEY }}
          script: |
            #!/bin/bash
            set -e
            echo "Starting deployment for branch '$BRANCH' on host '$DEPLOY_HOST'"
            echo "Current user: $(whoami)"
            echo "Home directory: $HOME"
            echo "Current directory: $(pwd)"
            echo "Shell: $SHELL"
            echo "PATH: $PATH"

            # Use system-installed Node.js
            if [ "$USE_NVM" == "false" ]; then
              echo "Using system-installed Node.js"
              export PATH="/usr/bin:$PATH"
              echo "Node version (system): $(node -v)"
            fi

            cd /var/www/emnd/ || { echo "Failed to change directory"; exit 1; }

            echo "Resetting any local changes..."
            git reset --hard HEAD

            echo "Deploying to branch: $BRANCH"
            git checkout $BRANCH
            git pull origin $BRANCH

            yarn --version || npm install -g yarn

            echo "Installing dependencies"
            yarn install

            echo "Building the app"
            yarn build

            echo "Reloading the app with PM2"
            pm2 reload my-app
